name: Scraping Scheduler

on:
  schedule:
    - cron: "0 12 * * 5" # Ejecuta todos los viernes a las 12:00 horas (UTC)
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run scraping script
      run: python productos_farmacia_desconeccion.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'MartinaZubaran'
        git config --global user.email 'martinazubaran@gmail.com'
        git add Medicamentos/productos_scrapeados.csv
        git commit -m 'Subiendo archivo CSV automáticamente desde GitHub Actions'
        git push
